services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    
  postgresql:
    image: postgres
    container_name: postgresql_db
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: product_db
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - "microservices"

volumes:
  mongo:
  postgres:

networks:
  microservices:
    driver: bridge