# ================================
# = MONGODB CONFIGURATION
# ================================
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=customer_db
spring.data.mongodb.username=root
spring.data.mongodb.password=password
spring.data.mongodb.authentication-database=admin

# ================================
# = LOGGING CONFIGURATION
# ================================
logging.level.root=INFO
logging.level.com.ecommerce.customer_service=WARN
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Para el archivo que se creo
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.file.name=logs/customer-microservice.log
logging.file.max-size=10MB
logging.file.max-history=30

# ================================
# = SERVER CONFIGURATION
# ================================
server.port=8091
