server.port=8092

spring.datasource.url=jdbc:postgresql://localhost:5432/product_db
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



# ================================
# = LOGGING CONFIGURATION
# ================================
logging.level.root=INFO
logging.level.com.ecommerce.product_microservice=WARN
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Para el archivo que se creo
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.file.name=logs/product-microservice.log
logging.file.max-size=10MB
logging.file.max-history=30